# Generated by Django 4.2.23 on 2025-06-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='user_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
